### ISSUE TITLE
Already furry check fails when HumanRace used as possible race.

### ISSUE THREAD

**Issue by LunaLycan287** [BadDogSkyrim/Modding-Tools#6]
https://github.com/BadDogSkyrim/Modding-Tools/blob/2f5008ed930b2b177219b614a878b16e85f11cb4/FO4Edit/Edit%20Scripts/FFO_Furrifier.pas#L1567-L1576

If you want to still have humans in your game and want to set a probability for them with `SetClassProb(CLASS, 'HumanRace', 42)` this check will result in issues making the script think that all humans are 'already furry'.

As a workaround I used the following check, though that is just hacked in and could probably be written way cleaner:
```pascal
    race := GetNPCRace(npc);
    if result > 0 then begin
        // If already furry, do nothing
        if (masterRaceList.IndexOf(EditorID(race)) >= 0) 
            or (childRaceList.IndexOf(EditorID(race)) >= 0)
        then begin
            if (EditorID(race) <> 'HumanRace') 
                and (EditorID(race) <> 'HumanChildRace') 
            then begin
                if LOGGING then LogD('Already furry: ' + RaceIDtoStr(RaceIndex(race)));
                result := 0;
            end;
        end;
    end; 
```

PS: in this I also added the race to be logged as debug info, I suggest that is also added to diagnose those kinds of issues faster.

**Comment by BadDogSkyrim** [comment]
Fixed in next release.
