### ISSUE TITLE
FFO_Furrifier.pas not reckognizing Hellhound or Snekdog as option for Ghoul Race. 

### ISSUE THREAD

**Issue by Celestial-Vixen** [BadDogSkyrim/Modding-Tools#8]
I have in FFO_Furrifier.pas
`GHOUL_RACE = 'K9_HellhoundRace';`
`GHOUL_CHILD_RACE = 'K9_HellhoundChildRace';`

In FFO_RaceProbabilities.pas I have uncommented all the relevant lines about Hellhound's Child Race.

When I run FFO_Furrifier.pas in xEdit64 - it defaults the Ghoul Race selection to Dobermanns, and leaves the Ghoul Child Race blank. The drop-down doesn't contain the K9_HellhoundRace (Nor does it contain the script's default snekdog race, for that matter).  

Attached are my furrifier scripts. 
[FurrifierScripts.zip](https://github.com/BadDogSkyrim/Modding-Tools/files/15369297/FurrifierScripts.zip)

I may have messed something up with the hellhound, but surely the default ghoulrace of snekdog should still appear as an option, right?

**Comment by Celestial-Vixen** [comment]
I seem to have found the cause - if a race doesn't appear anywhere in `Procedure SetRaceProbabilities();`, then it won't show up as a valid option for ghouls. Obvious workaround is to enter the desired ghoul race with a probability of 0 in a faction, but it'd be nice if FFO_Furrifier.pas detected the race that was entered manually inside itself as a option too.

**Comment by Celestial-Vixen** [comment]
Adding in the desired ghoul race with a probability of 0 does not allow the race's childRace to be selected, e.g. adding `SetClassProb(CLASS_MINUTEMEN, 'K9_HellhoundRace', 0);` enabled HellhoundRace for ghouls, did not enable HellhoundChildRace for child ghouls.

**Comment by Celestial-Vixen** [comment]
Okay, all these errors show up in xEdit64 on the uncommented Hellhound ChildRace face morphs. I'm not sure why these morphs don't work, when they're the same morphs for the other K9 races.
```
ERROR: Could not find face morph "Ears - Full" on race K9_HellhoundRace FEMALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = FEMALECHILD
ERROR: Path = Female Face Morphs
ERROR: RaceID = 00000000
ERROR: Could not find face morph "Cheeks" on race K9_HellhoundRace FEMALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = FEMALECHILD
ERROR: Path = Female Face Morphs
ERROR: RaceID = 00000000
ERROR: Could not find face morph "Nose - Full" on race K9_HellhoundRace FEMALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = FEMALECHILD
ERROR: Path = Female Face Morphs
ERROR: RaceID = 00000000
ERROR: Could not find face morph "Ears - Full" on race K9_HellhoundRace MALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = MALECHILD
ERROR: Path = Male Face Morphs
ERROR: RaceID = 00000000
ERROR: Could not find face morph "Cheeks" on race K9_HellhoundRace MALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = MALECHILD
ERROR: Path = Male Face Morphs
ERROR: RaceID = 00000000
ERROR: Could not find face morph "Nose - Full" on race K9_HellhoundRace MALECHILD
ERROR: Morphlist is NOT assigned
ERROR: Race index = 3, [3] K9_HellhoundRace
ERROR: Sex = MALECHILD
ERROR: Path = Male Face Morphs
ERROR: RaceID = 00000000
```

**Comment by BadDogSkyrim** [comment]
Is this still an issue? There was a bunch of chat about something that looked a lot like this on Discord. Also, I updated the furrifier and it's worth trying with that.

If it is still not working post the current version of your scripts and I'll look.
